title: Automate Sketch
author: Ashung Hung
email: Ashung.hung@foxmail.com
keywords: [sketch, plugin, sketchplugin]
description: "Automate Sketch is a collection of plugins for Bohemian Coding's Sketch.app."
baseurl: ""
ghpageUrl: "http://ashung.github.io/Automate-Sketch/"
projectUrl: "https://github.com/Ashung/Automate-Sketch/"
